#!/usr/bin/env bash
# Entering this repository's dev shell from ANOTHER git repository writes
# nothing into that repository.
#
# The dev shell's hook installs git hooks (`.pre-commit-config.yaml`, hooks
# under `.git/hooks`, `core.hooksPath`). git-hooks.nix aims them at
# `git rev-parse --show-toplevel` of the CURRENT DIRECTORY, so without a guard
# `nix develop /path/to/this-repo` run from a sibling checkout plants this
# repository's hooks there: an untracked file that blocks that repository's
# pre-push gate, and foreign checks on its commits. flake.nix runs the hook only
# when the enclosing repository is this one.
#
# Asserted, from a scratch git repository and from a subdirectory of it: no
# file or directory appears, no hook is
# installed and `core.hooksPath` is untouched. As the positive control, entered
# from inside this repository the committed regular config stays byte-exact
# and the genuine canonical local hook is reconciled with the matching managed hook.
#
#   bash tests/test_dev_shell_writes_nothing_elsewhere.sh
set -euo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRATCH="$(mktemp -d)"
trap 'rm -rf "$SCRATCH"' EXIT
fail() {
    echo "FAIL: $*" >&2
    exit 1
}

git -C "$SCRATCH" init -q
git -C "$SCRATCH" -c user.name=t -c user.email=t@t commit -q --allow-empty -m init
mkdir -p "$SCRATCH/sub"
hooks_before="$(ls "$SCRATCH/.git/hooks")"

for dir in "$SCRATCH" "$SCRATCH/sub"; do
    (cd "$dir" && nix develop "$REPO" --no-write-lock-file -c true) >/dev/null 2>&1 \
        || fail "the dev shell did not start from $dir"
    [ -z "$(git -C "$SCRATCH" status --porcelain --ignored)" ] \
        || fail "entered from $dir: files were written into the other repository: $(git -C "$SCRATCH" status --porcelain --ignored | tr '\n' ' ')"
    # git status does not list empty directories.
    extra="$(cd "$SCRATCH" && find . -mindepth 1 -path ./.git -prune -o ! -path ./sub -print)"
    [ -z "$extra" ] || fail "entered from $dir: entries were created in the other repository: $(echo $extra)"
    [ "$(ls "$SCRATCH/.git/hooks")" = "$hooks_before" ] \
        || fail "entered from $dir: git hooks were installed into the other repository"
    [ -z "$(git -C "$SCRATCH" config --local --get core.hooksPath || true)" ] \
        || fail "entered from $dir: the other repository's core.hooksPath was changed"
done

# Positive control: preserve the committed config and install the genuine chain.
CONFIG="$REPO/.pre-commit-config.yaml"
[ -f "$CONFIG" ] && [ ! -L "$CONFIG" ] \
    || fail "control: owning tracked config is not a regular file"
git -C "$REPO" ls-files --error-unmatch .pre-commit-config.yaml >/dev/null \
    || fail "control: owning config is not tracked"
config_before="$(sha256sum "$CONFIG" | cut -d' ' -f1)"
(cd "$REPO" && nix develop "$REPO" --no-write-lock-file -c true) >/dev/null 2>&1 \
    || fail "the dev shell did not start from this repository"
[ -f "$CONFIG" ] && [ ! -L "$CONFIG" ] \
    || fail "control: entering the shell changed the config file type"
[ "$(sha256sum "$CONFIG" | cut -d' ' -f1)" = "$config_before" ] \
    || fail "control: entering the shell changed committed config bytes"
HOOKS="$(git -C "$REPO" rev-parse --path-format=absolute --git-path hooks)"
[ ! -L "$HOOKS" ] && [ -d "$HOOKS" ] \
    || fail "control: effective hook directory is not owned regular directory"
for hook in pre-commit pre-commit.repro-local pre-commit.repro-managed; do
    [ ! -L "$HOOKS/$hook" ] && [ -f "$HOOKS/$hook" ] && [ -x "$HOOKS/$hook" ] \
        || fail "control: missing genuine executable hook $hook"
done
grep -Fq '# reprobuild hook dispatcher protocol=2' "$HOOKS/pre-commit" \
    || fail "control: matching managed dispatcher absent"
grep -Fxq 'export PREK_NO_FAST_PATH=1' "$HOOKS/pre-commit.repro-local" \
    || fail "control: persisted canonical selector absent"
grep -Fxq '# File generated by prek: https://github.com/j178/prek' "$HOOKS/pre-commit.repro-local" \
    || fail "control: genuine generated native Prek local hook absent"
grep -Fq 'reprobuild.managed-hook.v1.pre-commit.434c2eeac4079591' "$HOOKS/pre-commit.repro-managed" \
    || fail "control: expected matching managed contract absent"
echo "PASS: foreign shell writes nothing; owning committed config stays byte-exact with canonical local and matching managed hooks"
