#!/usr/bin/env python3
"""Install genuine pinned Prek hooks with documented canonical execution.

Install the owning pinned upstream checker implementations faithfully.
The helper transforms only the real generated Prek pre-commit script and leaves
its actual checker, executable and arguments intact, then reconciles managed
Repro hooks. All integration controls use real tools/filesystem; no mocks.
"""
from __future__ import annotations
import argparse
import hashlib
import os
from pathlib import Path
import shutil
import stat
import subprocess
import sys
import tempfile

CONTRACT = "reprobuild.managed-hook.v1.pre-commit.434c2eeac4079591"
EXPORT = b"export PREK_NO_FAST_PATH=1\n"
GENERATED = b"# File generated by prek: https://github.com/j178/prek\n"
# Exact former owning Python SDK-generated pre-commit 4.5.1 body only.
LEGACY_OWNED_SHA256 = "b8cdcbc55d325d5dca327bfbd99dc95e2213aca66e2546e7cce7cd5cbce7722f"

def run(argv: list[str], cwd: Path) -> str:
    return subprocess.check_output(argv, cwd=cwd, text=True, stderr=subprocess.STDOUT).strip()

def native_install_environment(env: dict[str, str], git: str, root: Path, hooks: Path) -> dict[str, str]:
    # Native Prek refuses a nonempty hooksPath, then installs in common/hooks.
    # Override only this child command after proving that same owned destination.
    if any(key == "GIT_CONFIG_COUNT" or key == "GIT_CONFIG_PARAMETERS"
            or key.startswith(("GIT_CONFIG_KEY_", "GIT_CONFIG_VALUE_")) for key in env):
        raise RuntimeError("ambiguous inherited Git command configuration")
    common = Path(run([git, "rev-parse", "--path-format=absolute", "--git-common-dir"], root))
    default_hooks = common / "hooks"
    if default_hooks.is_symlink() or default_hooks.resolve() != hooks:
        raise RuntimeError("native default hooks differ from verified owning hooks")
    # main already validates effective ownership, including its narrowly
    # qualified registered-worktree relative-path repair before installation.
    child = env.copy()
    child["GIT_CONFIG_COUNT"] = "1"
    child["GIT_CONFIG_KEY_0"] = "core.hooksPath"
    child["GIT_CONFIG_VALUE_0"] = ""
    return child

def selected_tool(name: str) -> str:
    found = shutil.which(name)
    if not found:
        raise RuntimeError(f"missing declared native tool: {name}")
    return str(Path(found).absolute())

# Entire genuine pinned native template, including whitespace and final newlines.
# Only its independently selected owning executable binding varies by native SDK.
NATIVE_TEMPLATE = b'#!/usr/bin/env bash\n# File generated by prek: https://github.com/j178/prek\n# ID: 182c10f181da4464a3eec51b83331688\n\n# Unset GIT_DIR to avoid git taking current directory as the git dir.\n# See:\n# https://github.com/pre-commit/pre-commit/issues/2295\n# https://www.spinics.net/lists/git/msg374197.html\nunset GIT_DIR\n\nARGS=(hook-impl --hook-type=pre-commit --script-version=3)\n\nHERE="$(cd "$(dirname "$0")" && pwd)"\nARGS+=(--hook-dir "$HERE" -- "$@")\nPREK="@OWNING_PREK_EXECUTABLE@"\n\n# Check if the full path to prek is executable, otherwise fallback to PATH\nif [ ! -x "$PREK" ]; then\n    PREK="prek"\nfi\n\nexec "$PREK" "${ARGS[@]}"\n\n'

def native_generated_body(prek: str) -> bytes:
    return NATIVE_TEMPLATE.replace(b"@OWNING_PREK_EXECUTABLE@", os.fsencode(prek))

def canonical_body(prek: str) -> bytes:
    native = native_generated_body(prek)
    first, rest = native.split(b"\n", 1)
    return first + b"\n" + EXPORT + rest

def canonical_generated_body(body: bytes, prek: str, mode: int) -> bytes:
    if mode != 0o755 or body != native_generated_body(prek):
        raise RuntimeError("unexpected exact owning native Prek hook body or mode")
    return canonical_body(prek)

def validate_prior_owned_body(body: bytes, mode: int, prek: str) -> None:
    if mode != 0o755:
        raise RuntimeError("former owning local hook mode changed")
    if hashlib.sha256(body).hexdigest() == LEGACY_OWNED_SHA256:
        return
    if body not in (native_generated_body(prek), canonical_body(prek)):
        raise RuntimeError("unknown or modified owning local hook body")

KNOWN_MANAGED_BODIES = {
    "pre-commit": "06cfcb59c42b99e9432c469f6bce7dc4fa5b0fa7c6f4f4e0548a1161233cf576",
    "pre-commit.repro-managed": "598ed91d257d1d236de042e708bd239837e069b2ee6fd583cf6b2d121f294507",
    "pre-push": "f5084841c5edfe6bfdaba3ad55c142b87e4e93b725754de0af553b57709e5c29",
    "pre-push.repro-managed": "642c37aca860a03ee6e7c2d0f941bf6fbdd1202c9f356c4fe68bf3ad3bfe6da6",
}

# Exact immutable native Git sample templates: former host2.54 and owning2.51.2.
# Git does not dispatch the .sample filename, even with its native0755 mode.
KNOWN_GIT_PRE_PUSH_SAMPLE_BODIES = {
    "f35ff977f07f76b61e0ebc047bf500793d22d95fbcf86c6ab95561b6ba339bc8",
    "7b9d5ae35b46834cbd02a674efcae68e76994e513058d825ecd65b7060d35c83",
}


def pre_push_inventory(hooks: Path) -> dict[str, tuple[bytes, int]]:
    inventory = {}
    if not hooks.exists():
        return inventory
    for path in hooks.iterdir():
        if not path.name.startswith("pre-push"):
            continue
        expected = KNOWN_MANAGED_BODIES.get(path.name)
        sample = path.name == "pre-push.sample"
        if expected is None and not sample:
            raise RuntimeError(f"unknown pre-push hook entry: {path.name}")
        metadata = path.lstat()
        if not stat.S_ISREG(metadata.st_mode):
            raise RuntimeError(f"unowned pre-push hook type: {path.name}")
        body = path.read_bytes()
        mode = stat.S_IMODE(metadata.st_mode)
        digest = hashlib.sha256(body).hexdigest()
        qualified_body = digest in KNOWN_GIT_PRE_PUSH_SAMPLE_BODIES if sample else digest == expected
        if mode != 0o755 or not qualified_body:
            raise RuntimeError(f"modified pre-push hook body or mode: {path.name}")
        inventory[path.name] = (body, mode)
    return inventory

OWNING_DECLARATIONS = (
    ".pre-commit-config.yaml", ".editorconfig", "flake.nix", "flake.lock",
    "nix/python.nix", ".python-version", "tools/python-sdk/default.nix",
    "tools/install-canonical-hooks.py",
)

def owned_common_directory(git: str, root: Path) -> Path:
    # Git registration and primary-owned metadata establish shared-hook ownership.
    raw_common = Path(run([git, "rev-parse", "--git-common-dir"], root))
    lexical_common = raw_common if raw_common.is_absolute() else root / raw_common
    if lexical_common.is_symlink():
        raise RuntimeError("symlink Git common directory")
    common = lexical_common.resolve(strict=True)
    records = subprocess.check_output(
        [git, "worktree", "list", "--porcelain", "-z"], cwd=root
    ).split(b"\0\0")
    registered = []
    for record in records:
        fields = record.split(b"\0")
        if fields and fields[0].startswith(b"worktree "):
            registered.append(Path(os.fsdecode(fields[0][9:])))
    if not registered or not any(path.resolve() == root for path in registered):
        raise RuntimeError("owning worktree is not registered")
    primary = registered[0]
    if primary.is_symlink() or not primary.is_dir():
        raise RuntimeError("primary worktree is not an owned regular directory")
    primary = primary.resolve(strict=True)
    primary_git = primary / ".git"
    if primary_git.is_symlink() or not primary_git.is_dir() or primary_git.resolve() != common:
        raise RuntimeError("Git common directory does not belong to registered primary")
    git_dir = Path(run([git, "rev-parse", "--absolute-git-dir"], root))
    if git_dir.is_symlink() or not git_dir.is_dir():
        raise RuntimeError("owning Git metadata is not a regular directory")
    resolved_git_dir = git_dir.resolve(strict=True)
    if root == primary:
        if resolved_git_dir != common:
            raise RuntimeError("primary Git metadata differs from common directory")
    else:
        if resolved_git_dir.parent != common / "worktrees":
            raise RuntimeError("linked worktree metadata is outside owning common directory")
        marker = root / ".git"
        if marker.is_symlink() or not marker.is_file():
            raise RuntimeError("linked worktree registration is not a regular file")
        registration = resolved_git_dir / "gitdir"
        if registration.is_symlink() or not registration.is_file():
            raise RuntimeError("missing genuine linked-worktree registration")
        if Path(registration.read_text().strip()).resolve(strict=True) != marker.resolve(strict=True):
            raise RuntimeError("linked-worktree registration points elsewhere")
    for name in OWNING_DECLARATIONS:
        current, original = root / name, primary / name
        for path in (current, original):
            if path.is_symlink() or not path.is_file():
                raise RuntimeError(f"owning declaration is not regular: {name}")
        if current.read_bytes() != original.read_bytes():
            raise RuntimeError(f"primary/current owning declaration differs: {name}")
    return common

def atomic_write(path: Path, data: bytes, mode: int) -> None:
    descriptor, filename = tempfile.mkstemp(prefix=".canonical-prek-", dir=path.parent)
    temporary = Path(filename)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        temporary.chmod(mode)
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repro", required=True, help="explicit measured matching managed-hook engine")
    parser.add_argument("--bootstrap-managed", action="store_true",
                        help="ownership-check and establish matching managed hooks before canonical installation")
    args = parser.parse_args()
    root = Path.cwd().resolve()
    git = selected_tool("git")
    prek = selected_tool("prek")
    repro = Path(args.repro).absolute()
    if not repro.is_file() or not os.access(repro, os.X_OK):
        raise RuntimeError("missing selected matching Repro executable")
    if Path(run([git, "rev-parse", "--show-toplevel"], root)).resolve() != root:
        raise RuntimeError("run from actual owning repository root")
    if not (root / ".pre-commit-config.yaml").is_file():
        raise RuntimeError("missing owning portable standard config")
    if run([prek, "--version"], root) != "prek 0.2.17":
        raise RuntimeError("unqualified native Prek version")
    if run([str(repro), "hooks", "protocol", "--require=2", "--hook-contract=" + CONTRACT], root) != "2":
        raise RuntimeError("matching managed hook protocol failed")
    common = owned_common_directory(git, root)
    hooks = common / "hooks"
    if hooks.is_symlink() or (hooks.exists() and not hooks.is_dir()):
        raise RuntimeError("own hooks directory is symlink or non-directory")
    configured = subprocess.run([git, "config", "--get", "core.hooksPath"], cwd=root, text=True, capture_output=True)
    if configured.returncode not in (0, 1):
        raise RuntimeError("cannot inspect own hook path")
    repair_registered_relative_path = False
    if configured.returncode == 0:
        raw = Path(configured.stdout.strip())
        scope = run([git, "config", "--show-scope", "--get", "core.hooksPath"], root).split()[0]
        repair_registered_relative_path = (
            str(raw) == ".git/hooks" and scope == "local" and not (root / ".git").is_dir()
        )
        resolved = (root / raw).resolve() if not raw.is_absolute() else raw.resolve()
        if resolved != hooks and not repair_registered_relative_path:
            raise RuntimeError("nonowning or unqualified hooks directory")
    actual_hooks = Path(run([git, "rev-parse", "--path-format=absolute", "--git-path", "hooks"], root))
    if actual_hooks.is_symlink() or (
        actual_hooks.resolve() != hooks.resolve() and not repair_registered_relative_path
    ):
        raise RuntimeError("effective Git hooks path is not the owning directory")
    if actual_hooks.exists() and not actual_hooks.is_dir():
        raise RuntimeError("effective hooks path is non-directory")
    for name, expected_hash in KNOWN_MANAGED_BODIES.items():
        path = hooks / name
        if path.is_symlink():
            raise RuntimeError(f"unowned managed hook symlink: {name}")
        if path.exists():
            if not path.is_file():
                raise RuntimeError(f"unowned managed hook type: {name}")
            body = path.read_bytes()
            if name == "pre-commit" and not body.startswith(b"#!/usr/bin/env sh\n# reprobuild hook dispatcher protocol=2\n"):
                validate_prior_owned_body(body, stat.S_IMODE(path.stat().st_mode), prek)
            elif hashlib.sha256(body).hexdigest() != expected_hash or stat.S_IMODE(path.stat().st_mode) != 0o755:
                raise RuntimeError(f"unknown or modified managed hook template: {name}")
    original_pre_push = pre_push_inventory(hooks)

    env = os.environ.copy()
    env["PREK_NO_FAST_PATH"] = "1"
    env["REPROBUILD_REPRO"] = str(repro)
    # The owning config requires language_version system; Prek refuses
    # managed Python downloads. The locked SDK supplies native Python on PATH.
    existing = hooks / "pre-commit"
    if existing.is_symlink():
        raise RuntimeError("unowned existing pre-commit symlink")
    if existing.exists():
        if existing.is_symlink() or not existing.is_file():
            raise RuntimeError("unowned existing pre-commit hook shape")
        previous = existing.read_bytes()
        if not previous.startswith(b"#!/usr/bin/env sh\n# reprobuild hook dispatcher protocol=2\n"):
            validate_prior_owned_body(previous, stat.S_IMODE(existing.stat().st_mode), prek)
    preserved = hooks / "pre-commit.repro-local"
    preserved_before = None
    if preserved.is_symlink():
        raise RuntimeError("unowned preserved local hook symlink")
    if preserved.exists():
        if preserved.is_symlink() or not preserved.is_file():
            raise RuntimeError("unowned preserved local hook shape")
        preserved_before = preserved.read_bytes()
        validate_prior_owned_body(preserved_before, stat.S_IMODE(preserved.stat().st_mode), prek)
    backup = None
    if preserved_before is not None:
        backup = hooks / ("pre-commit.repro-local.backup-" + hashlib.sha256(preserved_before).hexdigest())
        if backup.is_symlink() or (backup.exists() and (
            not backup.is_file() or backup.read_bytes() != preserved_before
            or stat.S_IMODE(backup.stat().st_mode) != stat.S_IMODE(preserved.stat().st_mode)
        )):
            raise RuntimeError("unowned preserved-template backup")
    if not args.bootstrap_managed and set(original_pre_push) - {"pre-push.sample"} != {"pre-push", "pre-push.repro-managed"}:
        raise RuntimeError("matching managed hooks must be established by ownership-checked caller bootstrap")
    install_env = native_install_environment(env, git, root, hooks)
    # All ownership/refusal checks precede the first directory or hook write.
    hooks.mkdir(exist_ok=True)
    if repair_registered_relative_path:
        # Repair only the verified primary-owned local legacy setting after all checks.
        subprocess.run([git, "config", "--local", "core.hooksPath", str(hooks)], cwd=root, check=True)
        effective = Path(run([git, "rev-parse", "--path-format=absolute", "--git-path", "hooks"], root))
        if effective.is_symlink() or effective.resolve() != hooks:
            raise RuntimeError("registered worktree hook path repair did not select owning common hooks")
    if args.bootstrap_managed:
        # Separate caller bootstrap: every ownership check above completed before
        # matching ensure creates any hook. Preserve existing pre-push entries.
        subprocess.run([str(repro), "hooks", "ensure", "--vcs", "."], cwd=root, env=env, check=True)
        current_pre_push = pre_push_inventory(hooks)
        expected_names = {"pre-push", "pre-push.repro-managed"} | (set(original_pre_push) & {"pre-push.sample"})
        if set(current_pre_push) != expected_names:
            raise RuntimeError("matching bootstrap did not create qualified pre-push hooks")
        for name, snapshot in original_pre_push.items():
            if current_pre_push.get(name) != snapshot:
                raise RuntimeError(f"bootstrap changed existing pre-push body or mode: {name}")
        for name, expected_hash in KNOWN_MANAGED_BODIES.items():
            target = hooks / name
            if target.is_symlink() or not target.is_file() or stat.S_IMODE(target.stat().st_mode) != 0o755:
                raise RuntimeError(f"bootstrap produced unowned managed hook shape: {name}")
            if hashlib.sha256(target.read_bytes()).hexdigest() != expected_hash:
                raise RuntimeError(f"bootstrap produced unexpected managed hook body: {name}")
        local = hooks / "pre-commit.repro-local"
        if local.is_symlink() or (local.exists() and not local.is_file()):
            raise RuntimeError("bootstrap produced unowned preserved local hook shape")
        if local.exists():
            local_body = local.read_bytes()
            validate_prior_owned_body(local_body, stat.S_IMODE(local.stat().st_mode), prek)
            if preserved_before is not None and local_body != preserved_before:
                raise RuntimeError("bootstrap changed preserved local hook body")
        elif preserved_before is not None:
            raise RuntimeError("bootstrap removed preserved local hook")
        print("Ownership-checked matching managed bootstrap complete")
        return
    persisted_config = subprocess.check_output([git, "config", "--null", "--show-origin", "--list"], cwd=root)
    try:
        subprocess.run([prek, "install", "--install-hooks"], cwd=root, env=install_env, check=True)
        generated = hooks / "pre-commit"
        if generated.is_symlink() or not generated.is_file():
            raise RuntimeError("actual generated local pre-commit is not owned regular file")
        body = generated.read_bytes()
        mode = stat.S_IMODE(generated.stat().st_mode)
        if not mode & stat.S_IXUSR:
            raise RuntimeError("generated native hook is not executable")
        canonical = canonical_generated_body(body, prek, mode)
        atomic_write(generated, canonical, mode)
        if preserved.is_symlink() or (preserved.exists() and not preserved.is_file()):
            raise RuntimeError("preserved local hook changed shape during installation")
        if preserved.exists() != (preserved_before is not None):
            raise RuntimeError("preserved local hook created or disappeared during installation")
        if preserved_before is not None:
            # Reconcile the already validated owning template, retaining its
            # exact former bytes before replacing only this local checker.
            if preserved.read_bytes() != preserved_before:
                raise RuntimeError("preserved local hook changed during installation")
            if backup is None:
                raise RuntimeError("missing validated former-template backup path")
            if backup.is_symlink() or (backup.exists() and (not backup.is_file() or backup.read_bytes() != preserved_before)):
                raise RuntimeError("former-template backup changed during installation")
            if not backup.exists():
                atomic_write(backup, preserved_before, stat.S_IMODE(preserved.stat().st_mode))
            atomic_write(preserved, canonical, mode)
    finally:
        # Even installation/template failure must leave the managed dispatcher
        # reconciled; no commit is attempted on a failed canonical installation.
        subprocess.run([str(repro), "hooks", "ensure", "--vcs", "."], cwd=root, env=env, check=True)
        if pre_push_inventory(hooks) != original_pre_push:
            raise RuntimeError("pre-push filename, shape, body or mode changed")
        if subprocess.check_output([git, "config", "--null", "--show-origin", "--list"], cwd=root) != persisted_config:
            raise RuntimeError("persisted Git configuration changed during native installation")
    local = hooks / "pre-commit.repro-local"
    if local.is_symlink() or not local.is_file() or stat.S_IMODE(local.stat().st_mode) != 0o755 or local.read_bytes() != canonical:
        raise RuntimeError("reconciled local hook did not preserve canonical native script")
    if pre_push_inventory(hooks) != original_pre_push:
        raise RuntimeError("pre-push filename, shape, body or mode changed")
    print("Canonical pinned hook installed; local bytes SHA256=" + hashlib.sha256(canonical).hexdigest())

if __name__ == "__main__":
    main()
