[meta]
name = "click-test"
version = 1

[scope]
default_exec = "trace"
default_value_action = "allow"

[[scope.rules]]
selector = 'pkg:glob:click*'
exec = 'trace'

[[scope.rules.value_patterns]]
selector = "global:glob:*"
action = "drop"

[[scope.rules]]
selector = 'pkg:glob:test*'
exec = 'trace'

[[scope.rules.value_patterns]]
selector = "global:glob:*"
action = "drop"

[[scope.rules]]
selector = 'pkg:glob:pytest*'
exec = "skip"

[[scope.rules]]
selector = 'pkg:glob:_pytest*'
exec = 'skip'

[[scope.rules]]
selector = 'pkg:glob:pluggy*'
exec = 'skip'
