name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests on ${{ matrix.os }} (Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
      - name: Install Python via uv
        shell: bash
        run: uv python install ${{ matrix.python-version }}
      - name: Run tests
        shell: bash
        run: uv run -p ${{ matrix.python-version }} -m unittest discover -v

  nix-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.05
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Run tests via Nix
        run: nix develop --command just test

  rust-smoke:
    name: Rust module smoke test on ${{ matrix.os }} (Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v4
      - uses: messense/maturin-action@v1
        with:
          command: build
          args: --interpreter python${{ matrix.python-version }} -m crates/codetracer-python-recorder/Cargo.toml --release
      - name: Install and smoke test built wheel with uv (pytest)
        shell: bash
        run: uv run -p ${{ matrix.python-version }} -m pip install crates/codetracer-python-recorder/target/wheels/*.whl && uv run -p ${{ matrix.python-version }} --with pytest -- python -m pytest crates/codetracer-python-recorder/test -q
